### ISSUE TITLE
(max?) width issue

### ISSUE THREAD

**Issue by jcolomb** [pfh/langevitour#2]
In my case (quarto website) setting width to 100% (or 200%) does not change the size of the plot, it just move the second column of the legend to the right.

indeed the maximal height is being set and constrains the width of the plot.

**Comment by pfh** [comment]
Hi Julien. The plot is always square, by design, so you will need to increase the height as well.

**Comment by jcolomb** [comment]
```
width="100%",
  height ="100vh"
``` 
seems to do what I expected (as big as possible in Both height and width)

**Comment by pfh** [comment]
Great!

There is also always the fullscreen mode button.
